In [1]:
# import tweepy
# import csv
# import pandas as pd
# # input your credentials here

# consumerKeyconsume ='RXzVf0QoLzycPCzSyM672LYEr'
# consumerSecret='LXJ82qRr6i685209qfTcsRxgzHqYyFdW6O2ee81a9CCSBd3cOV'
# accessToken='839494478171947009-uMN3BaDGHRD0RQJPSMtSVVk49HQociR'
# accessTokenSecret='uudOqmoknxb1sjrKlTG4UOJIYY4j3OtJz8EUZXjk3kJYp'

# auth = tweepy.OAuthHandler(consumerKeyconsume, consumerSecret)
# auth.set_access_token(accessToken, accessTokenSecret)
# api = tweepy.API(auth,wait_on_rate_limit=True)

# # Open/Create a file to write data
# csvFile = open('sampletwitter.csv', 'w')
# #Use csv Writer
# csvWriter = csv.writer(csvFile)
# max_tweets = 10000

# for tweet in tweepy.Cursor(api.search,q="#trump",count=100,
#                            lang="en",
#                            since="2019-09-26", limit=max_tweets).items(max_tweets):
#     outTweets = [tweet.id_str, tweet.created_at, tweet.text.encode("utf-8"), 
#               tweet.favorite_count, tweet.retweet_count ]
#     print (tweet.id_str, tweet.created_at, tweet.text.encode("utf-8"), 
#               tweet.favorite_count, tweet.retweet_count)
    
#     csvWriter.writerow([tweet.id_str, tweet.created_at, tweet.text.encode("utf-8"), 
#               tweet.favorite_count, tweet.retweet_count])

In [42]:
headers= ('id', 'date', 'tweet', 'fave', 'retweet')
file = pd.read_csv('sampletwitter.csv', header=0)
file.columns = headers
file.head(10)

,id,date,tweet,fave,retweet
0,1177252906040475654,2019-09-26 16:05:39,b'RT @MazJobrani: #TBT a few weeks ago @Flappe...,0,4
1,1177252901707812865,2019-09-26 16:05:38,b'RT @ap236: President Donald Trump incredulou...,0,1
2,1177252897030995969,2019-09-26 16:05:37,b'RT @mog7546: Whistleblower: #Trump used powe...,0,30
3,1177252895298850818,2019-09-26 16:05:37,b'#trump\xe2\x80\x99s other #Ukraine problem: ...,0,0
4,1177252895047192576,2019-09-26 16:05:37,b'RT @Emolclause: #BREAKING:Now #CNN reports t...,0,197
5,1177252889082777600,2019-09-26 16:05:35,b'RT @mog7546: BEST SONG OF THE YEAR!!!\n\nDon...,0,83
6,1177252881126182912,2019-09-26 16:05:33,b'I Will Convert Or Clone Any Web Page Into El...,0,0
7,1177252873438187521,2019-09-26 16:05:31,b'RT @CH_Americas: Senior Research Fellow @lin...,0,6
8,1177252866215546882,2019-09-26 16:05:30,b'Point is - Joe #Biden obstructd justice in U...,0,0
9,1177252859265478657,2019-09-26 16:05:28,b'RT @CaliDeplorable: @always_andie @TheDemocr...,0,19

In [43]:
import re
def data_cleansing(corpus):
        remove_hash = re.sub("#\S+", " ", str(corpus))

        remove_pic = re.sub("pic\S+", " ", str(remove_hash))

        remove_at = re.sub("@\S+", " ", str(remove_pic))

        remove_special = re.sub("[^a-zA-Z.\d\s]", " ", str(remove_at))

        remove_rt = re.sub("^b.RT", " ", str(remove_special))

        words = remove_rt.lower().split()
        return (" ".join(words))

In [44]:
file['tweet'] = file['tweet'].apply(lambda x:data_cleansing(x))

In [45]:
file.head()

,id,date,tweet,fave,retweet
0,1177252906040475654,2019-09-26 16:05:39,a few weeks ago i guess this is what happens w...,0,4
1,1177252901707812865,2019-09-26 16:05:38,president donald trump incredulous after his m...,0,1
2,1177252897030995969,2019-09-26 16:05:37,whistleblower used power of office to get ukra...,0,30
3,1177252895298850818,2019-09-26 16:05:37,b other problem new concern about his business...,0,0
4,1177252895047192576,2019-09-26 16:05:37,reports that officials moved communications be...,0,197

In [46]:
import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
nltk.download('vader_lexicon')
def sentiment_val(text):
    analyser = SentimentIntensityAnalyzer()
    result = analyser.polarity_scores(text)
    score = result['compound']
    return round(score,1)

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\iriss\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

In [47]:
#running a sample on one line just make sure the sentiment analyser works

sample = file['tweet'][20]
print(sample)
print(sentiment_val(sample))

we screwed up bigly n n aides already regret releasing damning ukraine call readout n nlet xe2 x80 x99s get back to total screcy... cov xe2 x80 xa6
-0.8

In [48]:
tweets = file['tweet']
all_sent_val = []
all_sentiments=[]

for i in range(0, len(file)):
    all_sent_val.append(sentiment_val(tweets[i]))

In [49]:
file['sentiment_value'] = all_sent_val

In [50]:
file.head()

,id,date,tweet,fave,retweet,sentiment_value
0,1177252906040475654,2019-09-26 16:05:39,a few weeks ago i guess this is what happens w...,0,4,0.1
1,1177252901707812865,2019-09-26 16:05:38,president donald trump incredulous after his m...,0,1,-0.7
2,1177252897030995969,2019-09-26 16:05:37,whistleblower used power of office to get ukra...,0,30,-0.4
3,1177252895298850818,2019-09-26 16:05:37,b other problem new concern about his business...,0,0,-0.4
4,1177252895047192576,2019-09-26 16:05:37,reports that officials moved communications be...,0,197,0.0